packages = ["sudo"]
script = """
set -eux

useradd -m ${ALMA_USER}
passwd ${ALMA_USER}
echo "%wheel ALL=(ALL) ALL" > /etc/sudoers.d/wheel
usermod -G users,lp,video,network,storage,wheel,audio -a ${ALMA_USER}
"""
environment_variables = ["ALMA_USER"]
